# Generated by Django 3.0.4 on 2020-06-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_image', models.ImageField(upload_to='uploads/input_image')),
                ('base64_conversion', models.CharField(max_length=2000)),
                ('MD5_hash_string', models.CharField(max_length=40)),
            ],
        ),
    ]
